# Block volume, created on demand and attached to whichever node runs the pod.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-data-pvc
  namespace: week3-lab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: oci-bv-balanced
  resources:
    requests:
      storage: 50Gi
